name: .NET Core

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup FTP Software
      run: sudo apt-get update && apt-get install lftp
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create publish version
      run: dotnet publish
    - name: Deploy to Self Service Portal
      run: lftp -e "open ${{ HOST }}; user ${{ USERNAME }} ${{ PASSWORD }}; mirror -R --verbose --delete ${{ LOCAL_DIR }} ${{ REMOTE_DIR }} --exclude .git/;"
